"""
Document Generation Service
Uses Jinja2 templates to generate project documentation
"""

import os
from pathlib import Path
from jinja2 import Environment, FileSystemLoader, Template
from typing import Dict, Any
from ..models.charter import CharterData


class DocumentGenerator:
    """Generates project documents from templates"""
    
    def __init__(self, template_dir: str = None):
        if template_dir is None:
            # Default to app/templates/documents
            base_dir = Path(__file__).parent.parent
            template_dir = base_dir / "templates" / "documents"
        
        self.env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            trim_blocks=True,
            lstrip_blocks=True
        )
    
    def generate_charter(self, charter_data: CharterData, output_path: str = None) -> str:
        """Generate PROJECT_CHARTER.md from template"""
        template = self.env.get_template("PROJECT_CHARTER.md.j2")
        content = template.render(charter_data.model_dump())
        
        if output_path:
            with open(output_path, 'w') as f:
                f.write(content)
        
        return content
    
    def generate_readme(self, charter_data: CharterData, output_path: str = None) -> str:
        """Generate README.md from template"""
        # For now, simple template
        content = f"""# {charter_data.project_title}

## Overview

{charter_data.project_goal}

**Project Type:** {charter_data.project_type}  
**Status:** Initiating

## Problem Statement

{charter_data.problem_definition}

## Proposed Solution

{charter_data.proposed_solution}

## Success Criteria

{charter_data.success_criteria}

## Project Timeline

{charter_data.schedule_overview}

## Documentation

- [PROJECT_CHARTER.md](docs/PROJECT_CHARTER.md) - Detailed project charter
- [PROJECT_PLAN.md](docs/PROJECT_PLAN.md) - Work breakdown and schedule
- [ISSUES.md](ISSUES.md) - Task tracking and status

## Quick Start

See [QUICKSTART.md](QUICKSTART.md) for setup instructions.

---

*Generated by Project Wizard*
"""
        
        if output_path:
            with open(output_path, 'w') as f:
                f.write(content)
        
        return content
